export const MOCK_CATEGORIES = [
  { id: '1', name_ar: 'إلكترونيات', name_fr: 'Électronique', name_en: 'Electronics', icon: 'cpu', color: '#3B82F6', is_active: true, sort_order: 1 },
  { id: '2', name_ar: 'مواد البناء', name_fr: 'Matériaux de construction', name_en: 'Construction', icon: 'building', color: '#F59E0B', is_active: true, sort_order: 2 },
  { id: '3', name_ar: 'الغذاء والمشروبات', name_fr: 'Alimentation', name_en: 'Food & Beverages', icon: 'utensils', color: '#10B981', is_active: true, sort_order: 3 },
  { id: '4', name_ar: 'الملابس والنسيج', name_fr: 'Textile', name_en: 'Textile', icon: 'shirt', color: '#8B5CF6', is_active: true, sort_order: 4 },
  { id: '5', name_ar: 'الآلات والمعدات', name_fr: 'Machines', name_en: 'Machinery', icon: 'settings', color: '#EF4444', is_active: true, sort_order: 5 },
  { id: '6', name_ar: 'الكيماويات', name_fr: 'Chimie', name_en: 'Chemicals', icon: 'flask-conical', color: '#06B6D4', is_active: true, sort_order: 6 },
  { id: '7', name_ar: 'الأثاث', name_fr: 'Mobilier', name_en: 'Furniture', icon: 'armchair', color: '#D97706', is_active: true, sort_order: 7 },
  { id: '8', name_ar: 'السيارات', name_fr: 'Automobile', name_en: 'Automotive', icon: 'car', color: '#1B3A5C', is_active: true, sort_order: 8 },
];

export const MOCK_SUPPLIERS = [
  {
    id: 's1',
    profile_id: 'p1',
    company_name: 'شركة الجزائر للتكنولوجيا',
    company_name_fr: 'Algérie Tech SARL',
    description: 'رائدون في توريد الإلكترونيات والمعدات التقنية في الجزائر',
    logo_url: null,
    cover_url: null,
    category_id: '1',
    rating: 4.8,
    total_reviews: 234,
    total_sales: 1250000,
    is_verified: true,
    is_active: true,
    country: 'DZ',
    city: 'الجزائر العاصمة',
    min_order_amount: 50000,
    response_time: '2 ساعة',
    established_year: 2010,
    badges: ['trusted', 'premium', 'bestSeller'],
  },
  {
    id: 's2',
    profile_id: 'p2',
    company_name: 'مؤسسة البناء الحديث',
    company_name_fr: 'Construction Moderne EURL',
    description: 'متخصصون في مواد البناء والإنشاء عالية الجودة',
    logo_url: null,
    cover_url: null,
    category_id: '2',
    rating: 4.6,
    total_reviews: 189,
    total_sales: 3200000,
    is_verified: true,
    is_active: true,
    country: 'DZ',
    city: 'وهران',
    min_order_amount: 100000,
    response_time: '4 ساعات',
    established_year: 2005,
    badges: ['trusted', 'qualityGuaranteed'],
  },
  {
    id: 's3',
    profile_id: 'p3',
    company_name: 'مجمع الغذاء الوطني',
    company_name_fr: 'Groupe Alimentaire National',
    description: 'توريد المواد الغذائية والمشروبات بالجملة لجميع أنحاء الجزائر',
    logo_url: null,
    cover_url: null,
    category_id: '3',
    rating: 4.9,
    total_reviews: 412,
    total_sales: 5600000,
    is_verified: true,
    is_active: true,
    country: 'DZ',
    city: 'قسنطينة',
    min_order_amount: 30000,
    response_time: '1 ساعة',
    established_year: 1998,
    badges: ['trusted', 'premium', 'bestSeller', 'freeShipping'],
  },
  {
    id: 's4',
    profile_id: 'p4',
    company_name: 'نسيج المغرب العربي',
    company_name_fr: 'Textile Maghreb SPA',
    description: 'الشركة الرائدة في صناعة وتوريد المنسوجات والملابس',
    logo_url: null,
    cover_url: null,
    category_id: '4',
    rating: 4.5,
    total_reviews: 156,
    total_sales: 890000,
    is_verified: true,
    is_active: true,
    country: 'DZ',
    city: 'تلمسان',
    min_order_amount: 25000,
    response_time: '3 ساعات',
    established_year: 2012,
    badges: ['qualityGuaranteed', 'freeShipping'],
  },
  {
    id: 's5',
    profile_id: 'p5',
    company_name: 'الآلات الصناعية الجزائرية',
    company_name_fr: 'Machines Industrielles Algériennes',
    description: 'توريد وصيانة الآلات والمعدات الصناعية الثقيلة',
    logo_url: null,
    cover_url: null,
    category_id: '5',
    rating: 4.7,
    total_reviews: 98,
    total_sales: 7800000,
    is_verified: true,
    is_active: true,
    country: 'DZ',
    city: 'عنابة',
    min_order_amount: 500000,
    response_time: '6 ساعات',
    established_year: 2003,
    badges: ['trusted', 'premium'],
  },
];

export const MOCK_PRODUCTS = [
  {
    id: 'p1',
    supplier_id: 's1',
    category_id: '1',
    name_ar: 'لابتوب ديل بروفيشنال',
    name_fr: 'Dell Professional Laptop',
    name_en: 'Dell Professional Laptop',
    description_ar: 'لابتوب احترافي مناسب للأعمال التجارية مع معالج قوي وذاكرة عالية',
    price: 180000,
    currency: 'DZD',
    min_order_qty: 5,
    unit: 'قطعة',
    stock_qty: 200,
    is_active: true,
    is_featured: true,
    rating: 4.7,
    total_reviews: 45,
    total_orders: 320,
    images: [],
  },
  {
    id: 'p2',
    supplier_id: 's1',
    category_id: '1',
    name_ar: 'شاشة سامسونج 27 بوصة',
    name_fr: 'Écran Samsung 27 pouces',
    name_en: 'Samsung 27" Monitor',
    description_ar: 'شاشة احترافية عالية الدقة مناسبة لبيئات العمل',
    price: 65000,
    currency: 'DZD',
    min_order_qty: 10,
    unit: 'قطعة',
    stock_qty: 500,
    is_active: true,
    is_featured: true,
    rating: 4.5,
    total_reviews: 89,
    total_orders: 670,
    images: [],
  },
  {
    id: 'p3',
    supplier_id: 's2',
    category_id: '2',
    name_ar: 'أسمنت بورتلاند 50 كغ',
    name_fr: 'Ciment Portland 50 kg',
    name_en: 'Portland Cement 50 kg',
    description_ar: 'أسمنت بورتلاند عالي الجودة للبناء والإنشاء',
    price: 1500,
    currency: 'DZD',
    min_order_qty: 100,
    unit: 'كيس',
    stock_qty: 50000,
    is_active: true,
    is_featured: false,
    rating: 4.8,
    total_reviews: 234,
    total_orders: 12500,
    images: [],
  },
  {
    id: 'p4',
    supplier_id: 's3',
    category_id: '3',
    name_ar: 'زيت الزيتون الفاخر',
    name_fr: "Huile d'olive premium",
    name_en: 'Premium Olive Oil',
    description_ar: 'زيت زيتون طبيعي فاخر من أجود المناطق الجزائرية',
    price: 2800,
    currency: 'DZD',
    min_order_qty: 50,
    unit: 'لتر',
    stock_qty: 10000,
    is_active: true,
    is_featured: true,
    rating: 4.9,
    total_reviews: 156,
    total_orders: 4500,
    images: [],
  },
  {
    id: 'p5',
    supplier_id: 's4',
    category_id: '4',
    name_ar: 'قماش قطني عالي الجودة',
    name_fr: 'Tissu coton haute qualité',
    name_en: 'High Quality Cotton Fabric',
    description_ar: 'قماش قطني طبيعي 100% مناسب للصناعات النسيجية',
    price: 850,
    currency: 'DZD',
    min_order_qty: 100,
    unit: 'متر',
    stock_qty: 25000,
    is_active: true,
    is_featured: true,
    rating: 4.6,
    total_reviews: 78,
    total_orders: 2300,
    images: [],
  },
  {
    id: 'p6',
    supplier_id: 's5',
    category_id: '5',
    name_ar: 'حفارة هيدروليكية صناعية',
    name_fr: 'Excavatrice hydraulique industrielle',
    name_en: 'Industrial Hydraulic Excavator',
    description_ar: 'حفارة هيدروليكية ثقيلة للمشاريع الصناعية الكبيرة',
    price: 15000000,
    currency: 'DZD',
    min_order_qty: 1,
    unit: 'وحدة',
    stock_qty: 12,
    is_active: true,
    is_featured: true,
    rating: 4.8,
    total_reviews: 23,
    total_orders: 45,
    images: [],
  },
];

export const MOCK_ORDERS = [
  { id: 'o1', buyer_id: 'b1', supplier_id: 's1', total: 900000, currency: 'DZD', status: 'delivered', created_at: '2024-01-15', items: [{ product_id: 'p1', qty: 5, price: 180000 }] },
  { id: 'o2', buyer_id: 'b1', supplier_id: 's3', total: 140000, currency: 'DZD', status: 'processing', created_at: '2024-02-20', items: [{ product_id: 'p4', qty: 50, price: 2800 }] },
  { id: 'o3', buyer_id: 'b1', supplier_id: 's2', total: 150000, currency: 'DZD', status: 'shipped', created_at: '2024-03-05', items: [{ product_id: 'p3', qty: 100, price: 1500 }] },
];

export const MOCK_RFQS = [
  { id: 'r1', buyer_id: 'b1', product_id: 'p1', quantity: 20, target_price: 160000, currency: 'DZD', message: 'نحتاج إلى 20 وحدة بسعر أفضل', status: 'negotiating', created_at: '2024-03-10', replies: [
    { id: 'rr1', rfq_id: 'r1', sender: 'supplier', price: 170000, message: 'أفضل سعر يمكننا تقديمه هو 170,000 دج للوحدة', created_at: '2024-03-11' },
    { id: 'rr2', rfq_id: 'r1', sender: 'buyer', price: 165000, message: 'هل يمكن التوصل إلى 165,000 دج؟', created_at: '2024-03-12' },
  ]},
  { id: 'r2', buyer_id: 'b1', product_id: 'p4', quantity: 500, target_price: 750, currency: 'DZD', message: 'طلب كبير، نرغب في خصم', status: 'pending', created_at: '2024-03-15', replies: [] },
];

export const MOCK_MESSAGES = [
  { id: 'm1', sender_id: 's1', receiver_id: 'b1', content: 'مرحباً، شكراً لاهتمامكم بمنتجاتنا. هل تحتاجون إلى معلومات إضافية؟', created_at: '2024-03-15T10:30:00', is_read: true },
  { id: 'm2', sender_id: 'b1', receiver_id: 's1', content: 'نعم، نريد معرفة إمكانية التسليم خلال أسبوع', created_at: '2024-03-15T10:45:00', is_read: true },
  { id: 'm3', sender_id: 's1', receiver_id: 'b1', content: 'بالطبع، يمكننا التسليم خلال 5 أيام عمل', created_at: '2024-03-15T11:00:00', is_read: false },
  { id: 'm4', sender_id: 's3', receiver_id: 'b1', content: 'لدينا عرض خاص على زيت الزيتون هذا الشهر', created_at: '2024-03-14T09:00:00', is_read: false },
];

export const MOCK_NOTIFICATIONS = [
  { id: 'n1', user_id: 'b1', type: 'rfq_reply', title: 'رد على طلب عرض سعر', body: 'ردّ المورد على طلب عرض السعر الخاص بك', is_read: false, created_at: '2024-03-15T10:00:00' },
  { id: 'n2', user_id: 'b1', type: 'order_update', title: 'تحديث الطلب', body: 'تم شحن طلبك رقم #O-003', is_read: false, created_at: '2024-03-14T15:00:00' },
  { id: 'n3', user_id: 'b1', type: 'message', title: 'رسالة جديدة', body: 'لديك رسالة جديدة من مجمع الغذاء الوطني', is_read: true, created_at: '2024-03-14T09:00:00' },
];

export const MOCK_ANALYTICS = {
  revenue: [120000, 185000, 210000, 175000, 290000, 340000, 280000, 420000, 380000, 510000, 460000, 590000],
  orders: [12, 18, 22, 17, 29, 34, 28, 42, 38, 51, 46, 59],
  months: ['يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر'],
  topProducts: [
    { name: 'لابتوب ديل', sales: 320, revenue: 57600000 },
    { name: 'شاشة سامسونج', sales: 670, revenue: 43550000 },
    { name: 'زيت الزيتون', sales: 4500, revenue: 12600000 },
  ],
  categoryBreakdown: [
    { name: 'إلكترونيات', percentage: 35, color: '#3B82F6' },
    { name: 'غذاء', percentage: 25, color: '#10B981' },
    { name: 'بناء', percentage: 20, color: '#F59E0B' },
    { name: 'نسيج', percentage: 12, color: '#8B5CF6' },
    { name: 'أخرى', percentage: 8, color: '#64748B' },
  ],
};
